networks:
  local_network:
    driver: bridge

services:
  app:
    build: .
    container_name: microservice_container
    env_file:
      - app/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    networks:
      - local_network
    volumes:
      - .:/app